# Generated by Django 5.2 on 2025-09-29 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_aggregator', '0004_comment_votes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(help_text='True for like, False for dislike')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='news_aggreg_article_d9f0aa_idx',
            old_name='news_aggre_article_7bc4f1_idx',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='news_aggreg_parent__782b90_idx',
            old_name='news_aggre_parent__e9a415_idx',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='news_aggreg_cached__8c7ade_idx',
            old_name='news_aggre_cached_sco_idx',
        ),
        migrations.RenameIndex(
            model_name='commentvote',
            new_name='news_aggreg_comment_5e924a_idx',
            old_name='news_aggre_vote_comment_idx',
        ),
        migrations.RenameIndex(
            model_name='commentvote',
            new_name='news_aggreg_user_id_540a25_idx',
            old_name='news_aggre_vote_user_idx',
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='commentflag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='commentvote',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='commentflag',
            index=models.Index(fields=['comment'], name='news_aggreg_comment_8fea76_idx'),
        ),
        migrations.AddField(
            model_name='articlelike',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='news_aggregator.newsarticle'),
        ),
        migrations.AddField(
            model_name='articlelike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='articlelike',
            index=models.Index(fields=['article', 'is_like'], name='news_aggreg_article_5b6475_idx'),
        ),
        migrations.AddIndex(
            model_name='articlelike',
            index=models.Index(fields=['user', 'created_at'], name='news_aggreg_user_id_3ea28d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='articlelike',
            unique_together={('user', 'article')},
        ),
    ]
