# Generated by Django 5.2 on 2025-10-08 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_author_data(apps, schema_editor):
    """Copy data from old 'author' field to new 'author_name' field"""
    NewsArticle = apps.get_model('news_aggregator', 'NewsArticle')
    for article in NewsArticle.objects.all():
        article.author_name = article.author
        article.save(update_fields=['author_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('news_aggregator', '0005_articlelike_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # First, add the new author_name field
        migrations.AddField(
            model_name='newsarticle',
            name='author_name',
            field=models.CharField(blank=True, help_text='Author name when author is not a registered user', max_length=200),
        ),
        # Copy data from author to author_name
        migrations.RunPython(migrate_author_data, reverse_code=migrations.RunPython.noop),
        # Now remove the old author field
        migrations.RemoveField(
            model_name='newsarticle',
            name='author',
        ),
        # Add other new fields
        migrations.AddField(
            model_name='newsarticle',
            name='author_user',
            field=models.ForeignKey(blank=True, help_text='User profile if the author is a registered reporter', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='posted_by',
            field=models.ForeignKey(help_text='User who posted/submitted this article', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='news_aggregator.newssource'),
        ),
    ]
