# Generated by Django 5.2 on 2025-10-09 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_root_comment(apps, schema_editor):
    """
    Populate root_comment field for existing comments.
    - Top-level comments (parent=None): root_comment = self
    - Nested comments: root_comment = parent's root_comment (traverse up to find root)
    """
    Comment = apps.get_model('news_aggregator', 'Comment')

    # First, set root_comment for all top-level comments (parent=None)
    top_level_comments = Comment.objects.filter(parent__isnull=True)
    for comment in top_level_comments:
        comment.root_comment = comment
        comment.save(update_fields=['root_comment'])

    # Then, set root_comment for nested comments by traversing up the tree
    # Process comments ordered by depth to ensure parents are processed first
    nested_comments = Comment.objects.filter(parent__isnull=False).order_by('depth')
    for comment in nested_comments:
        # Find the root by traversing up the parent chain
        current = comment.parent
        while current.parent is not None:
            current = current.parent
        # current is now the top-level comment
        comment.root_comment = current
        comment.save(update_fields=['root_comment'])


def reverse_populate_root_comment(apps, schema_editor):
    """Reverse migration: clear root_comment field"""
    Comment = apps.get_model('news_aggregator', 'Comment')
    Comment.objects.all().update(root_comment=None)


class Migration(migrations.Migration):

    dependencies = [
        ('news_aggregator', '0006_add_reporter_author_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='root_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_replies', to='news_aggregator.comment'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['root_comment', 'created_at'], name='news_aggreg_root_co_648aba_idx'),
        ),
        migrations.RunPython(populate_root_comment, reverse_populate_root_comment),
    ]
