# Generated by Django 5.2 on 2025-04-11 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news_aggregator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('political_filter', models.CharField(choices=[('all', 'Show All'), ('balanced', 'Balanced Mix'), ('neutral_only', 'Neutral Sources Only'), ('diverse', 'Diverse Viewpoints')], default='balanced', max_length=15)),
                ('enable_fact_check', models.BooleanField(default=True)),
                ('enable_bias_analysis', models.BooleanField(default=True)),
                ('enable_sentiment_analysis', models.BooleanField(default=True)),
                ('receive_misinformation_alerts', models.BooleanField(default=True)),
                ('daily_digest_email', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('preferred_sources', models.ManyToManyField(blank=True, related_name='preferred_by', to='news_aggregator.newssource')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
