# Generated by Django 5.0.2 on 2025-09-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='enable_logical_fallacy_analysis',
            field=models.BooleanField(default=True),
        ),
    ]
