# Generated by Django 5.2 on 2025-09-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userpreferences_enable_logical_fallacy_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='enable_key_insights',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='enable_summary_display',
            field=models.BooleanField(default=True),
        ),
    ]
