# Generated by Django 5.2 on 2025-10-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userpreferences_public_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_reporter',
            field=models.BooleanField(default=False, help_text='Can this user create and manage their own articles?'),
        ),
    ]
