# Generated by Django 5.2 on 2025-04-11 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news_aggregator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiasAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('political_leaning', models.CharField(choices=[('left', 'Left'), ('center-left', 'Center-Left'), ('center', 'Center'), ('center-right', 'Center-Right'), ('right', 'Right'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('bias_score', models.FloatField()),
                ('confidence', models.FloatField()),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bias_analysis', to='news_aggregator.newsarticle')),
            ],
        ),
        migrations.CreateModel(
            name='FactCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim', models.TextField()),
                ('rating', models.CharField(choices=[('true', 'True'), ('mostly_true', 'Mostly True'), ('half_true', 'Half True'), ('mostly_false', 'Mostly False'), ('false', 'False'), ('pants_on_fire', 'Pants on Fire'), ('unverified', 'Unverified')], default='unverified', max_length=20)),
                ('explanation', models.TextField()),
                ('sources', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact_checks', to='news_aggregator.newsarticle')),
            ],
        ),
        migrations.CreateModel(
            name='MisinformationAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('resolution_details', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('related_articles', models.ManyToManyField(related_name='misinformation_alerts', to='news_aggregator.newsarticle')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_score', models.FloatField()),
                ('positive_score', models.FloatField()),
                ('negative_score', models.FloatField()),
                ('neutral_score', models.FloatField()),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_analysis', to='news_aggregator.newsarticle')),
            ],
        ),
    ]
