# Generated by Django 5.0.2 on 2025-09-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_aggregator', '0001_initial'),
        ('news_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factcheckresult',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factcheckresult',
            name='last_verified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='factcheckresult',
            index=models.Index(fields=['rating'], name='news_analys_rating_8174a7_idx'),
        ),
        migrations.AddIndex(
            model_name='factcheckresult',
            index=models.Index(fields=['article', 'last_verified'], name='news_analys_article_0ac442_idx'),
        ),
    ]
