# Generated by Django 5.0.2 on 2025-09-11 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_aggregator', '0002_add_political_bias_fields'),
        ('news_analysis', '0002_factcheckresult_confidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogicalFallacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField()),
                ('example', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='news_analys_name_ce8872_idx')],
            },
        ),
        migrations.CreateModel(
            name='LogicalFallacyDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('evidence_excerpt', models.TextField(blank=True)),
                ('start_char', models.IntegerField(blank=True, null=True)),
                ('end_char', models.IntegerField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallacy_detections', to='news_aggregator.newsarticle')),
                ('fallacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='news_analysis.logicalfallacy')),
            ],
            options={
                'verbose_name': 'Logical Fallacy Detection',
                'verbose_name_plural': 'Logical Fallacy Detections',
                'indexes': [models.Index(fields=['article', 'fallacy'], name='news_analys_article_d50de1_idx')],
            },
        ),
    ]
