# Generated by Django 5.2 on 2025-09-11 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_aggregator', '0002_add_political_bias_fields'),
        ('news_analysis', '0004_populate_logical_fallacies'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rank', models.PositiveSmallIntegerField(default=0, help_text='0-based order index')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='news_aggregator.newsarticle')),
            ],
            options={
                'ordering': ['article', 'rank', 'id'],
                'indexes': [models.Index(fields=['article', 'rank'], name='news_analys_article_6429d9_idx')],
                'unique_together': {('article', 'rank')},
            },
        ),
    ]
